postgresql:
  image: quay.io/sameersbn/postgresql:9.4-5
  environment:
    - DB_USER=redmine
    - DB_PASS=password
    - DB_NAME=redmine_production
redmine:
  image: quay.io/sameersbn/redmine:3.1.1-2
  links:
    - postgresql:postgresql
  environment:
    - REDMINE_PORT=10083
  ports:
    - "10083:80"
